name: walkietalkie
description: A mobile app that serves as a walkie talkie over ip
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  record: ^5.1.2
  audioplayers: ^5.2.1
  flutter_webrtc: ^0.9.48
  firebase_core: ^3.15.0
  firebase_database: ^11.1.0
  firebase_data_connect: ^0.1.5
  provider: ^6.1.1
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

